version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ecommerce_auth_db
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
  java_app:
    image: ms1_ecommerce_auth_app:1.0.0
    container_name: ms1_ecommerce_auth_app
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/ecommerce_auth_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
